# Generated by Django 3.2.6 on 2021-11-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(verbose_name='Timestmap')),
                ('volume', models.FloatField(verbose_name='Volume')),
                ('interval', models.CharField(max_length=200)),
            ],
        ),
    ]
